[package]
name = "structures"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.181", features = ["derive"] }
serde_json = "1.0.104"
serde_with = { version = "3.2.0", features = ["time_0_3"] }
time = "0.3.25"
